### ISSUE TITLE
Privileged

### ISSUE THREAD

**Issue by fabianvf** [rileyschuit/Zoneminder-Ansible#1]
Great project, I'm just looking at getting it into openshift and I was wondering why you needed `--privileged=true`. Is that because apache likes to run as a privileged user? If so, would it be helpful for me to rewrite the apache config so that it doesn't require privileged access?

**Comment by rileyschuit** [comment]
IIRC it was for accessing dedicated video cards.  I will look into the functionality for just IP cameras and comment or update accordingly.  :)

**Comment by rileyschuit** [comment]
Updated README.  Committed for master branch and v1.30.4

Thanks!

**Comment by fabianvf** [comment]
Nice! That was some quick turnaround.
